project:
  type: book
  output-dir: docs

book:
  title: "Biology 305: Biostatistics"
  author: "Dr. Jacob C. Cooper & Dr. Melissa Wuellner"
  date: "`r format(Sys.time(), '%d %B, %Y')`"
  chapters:
    - index.qmd
    - intro_to_r.qmd
    - summary.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual